[features]
seeds = false
[programs.devnet]
metaplex_anchor_nft = "2DRLpc3UvKwqgZgkjEEzGBw24ThvFZwGtRDzyLjqzScz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/hans/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
